# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions


from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DesignKestraFlow(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.KestraFlow:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DesignKestraFlow", llm_response=llm_response, mode="request")
        return typing.cast(types.KestraFlow, __result__)

    def DesignRAGPipeline(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.RAGPipelineConfig:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DesignRAGPipeline", llm_response=llm_response, mode="request")
        return typing.cast(types.RAGPipelineConfig, __result__)

    def EvaluateRAGResult(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.RAGEvaluation:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="EvaluateRAGResult", llm_response=llm_response, mode="request")
        return typing.cast(types.RAGEvaluation, __result__)

    def ExtractResume(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Resume:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractResume", llm_response=llm_response, mode="request")
        return typing.cast(types.Resume, __result__)

    def GenerateKestraFlowYAML(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.KestraFlowYAML:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateKestraFlowYAML", llm_response=llm_response, mode="request")
        return typing.cast(types.KestraFlowYAML, __result__)

    def ParseDevelopmentTask(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.DevelopmentTask:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ParseDevelopmentTask", llm_response=llm_response, mode="request")
        return typing.cast(types.DevelopmentTask, __result__)

    def ParseRAGQuery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.RAGQuery:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ParseRAGQuery", llm_response=llm_response, mode="request")
        return typing.cast(types.RAGQuery, __result__)

    def ReviewCodeQuality(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.QualityReview:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ReviewCodeQuality", llm_response=llm_response, mode="request")
        return typing.cast(types.QualityReview, __result__)

    def SummarizeCrewRun(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CrewOutput:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SummarizeCrewRun", llm_response=llm_response, mode="request")
        return typing.cast(types.CrewOutput, __result__)

    def SynthesizeRAGResponse(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.RAGResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SynthesizeRAGResponse", llm_response=llm_response, mode="request")
        return typing.cast(types.RAGResponse, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DesignKestraFlow(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.KestraFlow:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DesignKestraFlow", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.KestraFlow, __result__)

    def DesignRAGPipeline(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.RAGPipelineConfig:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DesignRAGPipeline", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.RAGPipelineConfig, __result__)

    def EvaluateRAGResult(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.RAGEvaluation:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="EvaluateRAGResult", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.RAGEvaluation, __result__)

    def ExtractResume(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Resume:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractResume", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Resume, __result__)

    def GenerateKestraFlowYAML(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.KestraFlowYAML:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateKestraFlowYAML", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.KestraFlowYAML, __result__)

    def ParseDevelopmentTask(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.DevelopmentTask:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ParseDevelopmentTask", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.DevelopmentTask, __result__)

    def ParseRAGQuery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.RAGQuery:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ParseRAGQuery", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.RAGQuery, __result__)

    def ReviewCodeQuality(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.QualityReview:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ReviewCodeQuality", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.QualityReview, __result__)

    def SummarizeCrewRun(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CrewOutput:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SummarizeCrewRun", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CrewOutput, __result__)

    def SynthesizeRAGResponse(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.RAGResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SynthesizeRAGResponse", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.RAGResponse, __result__)

    