# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (15)
# #########################################################################

class AgentTaskResult(BaseModel):
    agent: typing.Optional[types.AgentRole] = None
    task_title: typing.Optional[str] = None
    status: typing.Optional[types.TaskStatus] = None
    summary: typing.Optional[str] = None
    artifacts: typing.List["CodeArtifact"]
    observations: typing.List[str]
    next_steps: typing.List[str]

class CodeArtifact(BaseModel):
    filename: typing.Optional[str] = None
    language: typing.Optional[types.CodeLanguage] = None
    content: typing.Optional[str] = None
    description: typing.Optional[str] = None
    dependencies: typing.List[str]

class CrewOutput(BaseModel):
    objective: typing.Optional[str] = None
    tasks: typing.List["AgentTaskResult"]
    quality_review: typing.Optional["QualityReview"] = None
    final_deliverables: typing.List["CodeArtifact"]

class DevelopmentTask(BaseModel):
    title: typing.Optional[str] = None
    description: typing.Optional[str] = None
    assigned_to: typing.Optional[types.AgentRole] = None
    expected_output: typing.Optional[str] = None
    acceptance_criteria: typing.List[str]
    dependencies: typing.List[str]

class DocumentChunk(BaseModel):
    id: typing.Optional[str] = None
    source: typing.Optional[str] = None
    doc_type: typing.Optional[types.DocumentType] = None
    content: typing.Optional[str] = None
    relevance_score: typing.Optional[float] = None
    metadata: typing.List[str]

class KestraFlow(BaseModel):
    id: typing.Optional[str] = None
    flow_namespace: typing.Optional[str] = None
    description: typing.Optional[str] = None
    inputs: typing.List["KestraInput"]
    tasks: typing.List["KestraFlowTask"]
    triggers: typing.List[str]
    labels: typing.List[str]

class KestraFlowTask(BaseModel):
    id: typing.Optional[str] = None
    type: typing.Optional[types.KestraTaskType] = None
    description: typing.Optional[str] = None
    depends_on: typing.List[str]
    config_hint: typing.Optional[str] = None

class KestraFlowYAML(BaseModel):
    flow: typing.Optional["KestraFlow"] = None
    yaml_content: typing.Optional[str] = None
    filename: typing.Optional[str] = None

class KestraInput(BaseModel):
    name: typing.Optional[str] = None
    type: typing.Optional[str] = None
    description: typing.Optional[str] = None
    required: typing.Optional[bool] = None
    default_value: typing.Optional[str] = None

class QualityReview(BaseModel):
    approved: typing.Optional[bool] = None
    score: typing.Optional[int] = None
    summary: typing.Optional[str] = None
    issues: typing.List[str]
    recommendations: typing.List[str]
    reviewed_artifacts: typing.List[str]

class RAGEvaluation(BaseModel):
    query: typing.Optional[str] = None
    response: typing.Optional["RAGResponse"] = None
    faithfulness: typing.Optional[float] = None
    relevance: typing.Optional[float] = None
    completeness: typing.Optional[float] = None
    hallucination_detected: typing.Optional[bool] = None
    notes: typing.Optional[str] = None

class RAGPipelineConfig(BaseModel):
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None
    embedding_model: typing.Optional[str] = None
    vector_store: typing.Optional[str] = None
    chunk_size: typing.Optional[int] = None
    chunk_overlap: typing.Optional[int] = None
    strategy: typing.Optional[types.RetrievalStrategy] = None
    reranker: typing.Optional[str] = None
    collection_name: typing.Optional[str] = None

class RAGQuery(BaseModel):
    query: typing.Optional[str] = None
    intent: typing.Optional[str] = None
    filters: typing.List[str]
    strategy: typing.Optional[types.RetrievalStrategy] = None
    top_k: typing.Optional[int] = None
    rerank: typing.Optional[bool] = None

class RAGResponse(BaseModel):
    answer: typing.Optional[str] = None
    confidence: typing.Optional[float] = None
    sources: typing.List["DocumentChunk"]
    reasoning: typing.Optional[str] = None
    follow_up_questions: typing.List[str]
    requires_more_context: typing.Optional[bool] = None

class Resume(BaseModel):
    name: typing.Optional[str] = None
    email: typing.Optional[str] = None
    experience: typing.List[str]
    skills: typing.List[str]

# #########################################################################
# Generated type aliases (0)
# #########################################################################
