# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        client: typing.Optional[str] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if client is not None:
            options["client"] = client
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    def DesignKestraFlow(self, objective: str,context: str,
        baml_options: BamlCallOptions = {},
    ) -> types.KestraFlow:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.DesignKestraFlow(objective=objective,context=context,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="DesignKestraFlow", args={
                "objective": objective,"context": context,
            })
            return typing.cast(types.KestraFlow, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def DesignRAGPipeline(self, use_case: str,constraints: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RAGPipelineConfig:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.DesignRAGPipeline(use_case=use_case,constraints=constraints,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="DesignRAGPipeline", args={
                "use_case": use_case,"constraints": constraints,
            })
            return typing.cast(types.RAGPipelineConfig, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def EvaluateRAGResult(self, query: str,response: str,sources: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RAGEvaluation:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.EvaluateRAGResult(query=query,response=response,sources=sources,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="EvaluateRAGResult", args={
                "query": query,"response": response,"sources": sources,
            })
            return typing.cast(types.RAGEvaluation, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Resume:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ExtractResume(resume=resume,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractResume", args={
                "resume": resume,
            })
            return typing.cast(types.Resume, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def GenerateKestraFlowYAML(self, objective: str,context: str,
        baml_options: BamlCallOptions = {},
    ) -> types.KestraFlowYAML:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.GenerateKestraFlowYAML(objective=objective,context=context,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="GenerateKestraFlowYAML", args={
                "objective": objective,"context": context,
            })
            return typing.cast(types.KestraFlowYAML, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ParseDevelopmentTask(self, raw_task: str,
        baml_options: BamlCallOptions = {},
    ) -> types.DevelopmentTask:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ParseDevelopmentTask(raw_task=raw_task,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ParseDevelopmentTask", args={
                "raw_task": raw_task,
            })
            return typing.cast(types.DevelopmentTask, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ParseRAGQuery(self, user_input: str,available_filters: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RAGQuery:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ParseRAGQuery(user_input=user_input,available_filters=available_filters,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ParseRAGQuery", args={
                "user_input": user_input,"available_filters": available_filters,
            })
            return typing.cast(types.RAGQuery, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ReviewCodeQuality(self, artifacts: str,criteria: str,
        baml_options: BamlCallOptions = {},
    ) -> types.QualityReview:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ReviewCodeQuality(artifacts=artifacts,criteria=criteria,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ReviewCodeQuality", args={
                "artifacts": artifacts,"criteria": criteria,
            })
            return typing.cast(types.QualityReview, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def SummarizeCrewRun(self, raw_output: str,
        baml_options: BamlCallOptions = {},
    ) -> types.CrewOutput:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.SummarizeCrewRun(raw_output=raw_output,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="SummarizeCrewRun", args={
                "raw_output": raw_output,
            })
            return typing.cast(types.CrewOutput, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def SynthesizeRAGResponse(self, query: str,retrieved_chunks: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RAGResponse:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.SynthesizeRAGResponse(query=query,retrieved_chunks=retrieved_chunks,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="SynthesizeRAGResponse", args={
                "query": query,"retrieved_chunks": retrieved_chunks,
            })
            return typing.cast(types.RAGResponse, __result__.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DesignKestraFlow(self, objective: str,context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.KestraFlow, types.KestraFlow]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="DesignKestraFlow", args={
            "objective": objective,"context": context,
        })
        return baml_py.BamlSyncStream[stream_types.KestraFlow, types.KestraFlow](
          __result__,
          lambda x: typing.cast(stream_types.KestraFlow, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.KestraFlow, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def DesignRAGPipeline(self, use_case: str,constraints: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.RAGPipelineConfig, types.RAGPipelineConfig]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="DesignRAGPipeline", args={
            "use_case": use_case,"constraints": constraints,
        })
        return baml_py.BamlSyncStream[stream_types.RAGPipelineConfig, types.RAGPipelineConfig](
          __result__,
          lambda x: typing.cast(stream_types.RAGPipelineConfig, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.RAGPipelineConfig, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def EvaluateRAGResult(self, query: str,response: str,sources: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.RAGEvaluation, types.RAGEvaluation]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="EvaluateRAGResult", args={
            "query": query,"response": response,"sources": sources,
        })
        return baml_py.BamlSyncStream[stream_types.RAGEvaluation, types.RAGEvaluation](
          __result__,
          lambda x: typing.cast(stream_types.RAGEvaluation, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.RAGEvaluation, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.Resume, types.Resume]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractResume", args={
            "resume": resume,
        })
        return baml_py.BamlSyncStream[stream_types.Resume, types.Resume](
          __result__,
          lambda x: typing.cast(stream_types.Resume, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Resume, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def GenerateKestraFlowYAML(self, objective: str,context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.KestraFlowYAML, types.KestraFlowYAML]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="GenerateKestraFlowYAML", args={
            "objective": objective,"context": context,
        })
        return baml_py.BamlSyncStream[stream_types.KestraFlowYAML, types.KestraFlowYAML](
          __result__,
          lambda x: typing.cast(stream_types.KestraFlowYAML, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.KestraFlowYAML, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ParseDevelopmentTask(self, raw_task: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.DevelopmentTask, types.DevelopmentTask]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ParseDevelopmentTask", args={
            "raw_task": raw_task,
        })
        return baml_py.BamlSyncStream[stream_types.DevelopmentTask, types.DevelopmentTask](
          __result__,
          lambda x: typing.cast(stream_types.DevelopmentTask, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.DevelopmentTask, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ParseRAGQuery(self, user_input: str,available_filters: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.RAGQuery, types.RAGQuery]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ParseRAGQuery", args={
            "user_input": user_input,"available_filters": available_filters,
        })
        return baml_py.BamlSyncStream[stream_types.RAGQuery, types.RAGQuery](
          __result__,
          lambda x: typing.cast(stream_types.RAGQuery, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.RAGQuery, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ReviewCodeQuality(self, artifacts: str,criteria: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.QualityReview, types.QualityReview]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ReviewCodeQuality", args={
            "artifacts": artifacts,"criteria": criteria,
        })
        return baml_py.BamlSyncStream[stream_types.QualityReview, types.QualityReview](
          __result__,
          lambda x: typing.cast(stream_types.QualityReview, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.QualityReview, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def SummarizeCrewRun(self, raw_output: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.CrewOutput, types.CrewOutput]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="SummarizeCrewRun", args={
            "raw_output": raw_output,
        })
        return baml_py.BamlSyncStream[stream_types.CrewOutput, types.CrewOutput](
          __result__,
          lambda x: typing.cast(stream_types.CrewOutput, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.CrewOutput, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def SynthesizeRAGResponse(self, query: str,retrieved_chunks: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.RAGResponse, types.RAGResponse]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="SynthesizeRAGResponse", args={
            "query": query,"retrieved_chunks": retrieved_chunks,
        })
        return baml_py.BamlSyncStream[stream_types.RAGResponse, types.RAGResponse](
          __result__,
          lambda x: typing.cast(stream_types.RAGResponse, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.RAGResponse, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DesignKestraFlow(self, objective: str,context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="DesignKestraFlow", args={
            "objective": objective,"context": context,
        }, mode="request")
        return __result__
    def DesignRAGPipeline(self, use_case: str,constraints: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="DesignRAGPipeline", args={
            "use_case": use_case,"constraints": constraints,
        }, mode="request")
        return __result__
    def EvaluateRAGResult(self, query: str,response: str,sources: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="EvaluateRAGResult", args={
            "query": query,"response": response,"sources": sources,
        }, mode="request")
        return __result__
    def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractResume", args={
            "resume": resume,
        }, mode="request")
        return __result__
    def GenerateKestraFlowYAML(self, objective: str,context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GenerateKestraFlowYAML", args={
            "objective": objective,"context": context,
        }, mode="request")
        return __result__
    def ParseDevelopmentTask(self, raw_task: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ParseDevelopmentTask", args={
            "raw_task": raw_task,
        }, mode="request")
        return __result__
    def ParseRAGQuery(self, user_input: str,available_filters: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ParseRAGQuery", args={
            "user_input": user_input,"available_filters": available_filters,
        }, mode="request")
        return __result__
    def ReviewCodeQuality(self, artifacts: str,criteria: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ReviewCodeQuality", args={
            "artifacts": artifacts,"criteria": criteria,
        }, mode="request")
        return __result__
    def SummarizeCrewRun(self, raw_output: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="SummarizeCrewRun", args={
            "raw_output": raw_output,
        }, mode="request")
        return __result__
    def SynthesizeRAGResponse(self, query: str,retrieved_chunks: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="SynthesizeRAGResponse", args={
            "query": query,"retrieved_chunks": retrieved_chunks,
        }, mode="request")
        return __result__
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DesignKestraFlow(self, objective: str,context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="DesignKestraFlow", args={
            "objective": objective,"context": context,
        }, mode="stream")
        return __result__
    def DesignRAGPipeline(self, use_case: str,constraints: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="DesignRAGPipeline", args={
            "use_case": use_case,"constraints": constraints,
        }, mode="stream")
        return __result__
    def EvaluateRAGResult(self, query: str,response: str,sources: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="EvaluateRAGResult", args={
            "query": query,"response": response,"sources": sources,
        }, mode="stream")
        return __result__
    def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractResume", args={
            "resume": resume,
        }, mode="stream")
        return __result__
    def GenerateKestraFlowYAML(self, objective: str,context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GenerateKestraFlowYAML", args={
            "objective": objective,"context": context,
        }, mode="stream")
        return __result__
    def ParseDevelopmentTask(self, raw_task: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ParseDevelopmentTask", args={
            "raw_task": raw_task,
        }, mode="stream")
        return __result__
    def ParseRAGQuery(self, user_input: str,available_filters: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ParseRAGQuery", args={
            "user_input": user_input,"available_filters": available_filters,
        }, mode="stream")
        return __result__
    def ReviewCodeQuality(self, artifacts: str,criteria: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ReviewCodeQuality", args={
            "artifacts": artifacts,"criteria": criteria,
        }, mode="stream")
        return __result__
    def SummarizeCrewRun(self, raw_output: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="SummarizeCrewRun", args={
            "raw_output": raw_output,
        }, mode="stream")
        return __result__
    def SynthesizeRAGResponse(self, query: str,retrieved_chunks: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="SynthesizeRAGResponse", args={
            "query": query,"retrieved_chunks": retrieved_chunks,
        }, mode="stream")
        return __result__
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))