# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (6)
# #########################################################################

class AgentRole(str, Enum):
    SuperDev = "SuperDev"
    PythonExpert = "PythonExpert"
    BAMLExpert = "BAMLExpert"
    LangGraphExpert = "LangGraphExpert"
    RAGExpert = "RAGExpert"
    SupabaseExpert = "SupabaseExpert"
    KestraExpert = "KestraExpert"
    QualitySupervisor = "QualitySupervisor"

class CodeLanguage(str, Enum):
    Python = "Python"
    YAML = "YAML"
    SQL = "SQL"
    BAML = "BAML"
    TypeScript = "TypeScript"
    Markdown = "Markdown"

class DocumentType(str, Enum):
    Code = "Code"
    Documentation = "Documentation"
    FlowYAML = "FlowYAML"
    SchemaBAML = "SchemaBAML"
    AgentPrompt = "AgentPrompt"
    TaskDescription = "TaskDescription"
    KnowledgeBase = "KnowledgeBase"

class KestraTaskType(str, Enum):
    Http = "Http"
    Python = "Python"
    BashScript = "BashScript"
    SubflowExec = "SubflowExec"
    PostgresQuery = "PostgresQuery"
    SupabaseHttp = "SupabaseHttp"
    FlowCondition = "FlowCondition"
    Parallel = "Parallel"
    Trigger = "Trigger"

class RetrievalStrategy(str, Enum):
    Semantic = "Semantic"
    Keyword = "Keyword"
    Hybrid = "Hybrid"
    GraphRAG = "GraphRAG"

class TaskStatus(str, Enum):
    Pending = "Pending"
    InProgress = "InProgress"
    Done = "Done"
    Rejected = "Rejected"

# #########################################################################
# Generated classes (15)
# #########################################################################

class AgentTaskResult(BaseModel):
    agent: AgentRole
    task_title: str
    status: TaskStatus
    summary: str
    artifacts: typing.List["CodeArtifact"]
    observations: typing.List[str]
    next_steps: typing.List[str]

class CodeArtifact(BaseModel):
    filename: str
    language: CodeLanguage
    content: str
    description: str
    dependencies: typing.List[str]

class CrewOutput(BaseModel):
    objective: str
    tasks: typing.List["AgentTaskResult"]
    quality_review: "QualityReview"
    final_deliverables: typing.List["CodeArtifact"]

class DevelopmentTask(BaseModel):
    title: str
    description: str
    assigned_to: AgentRole
    expected_output: str
    acceptance_criteria: typing.List[str]
    dependencies: typing.List[str]

class DocumentChunk(BaseModel):
    id: str
    source: str
    doc_type: DocumentType
    content: str
    relevance_score: float
    metadata: typing.List[str]

class KestraFlow(BaseModel):
    id: str
    flow_namespace: str
    description: str
    inputs: typing.List["KestraInput"]
    tasks: typing.List["KestraFlowTask"]
    triggers: typing.List[str]
    labels: typing.List[str]

class KestraFlowTask(BaseModel):
    id: str
    type: KestraTaskType
    description: str
    depends_on: typing.List[str]
    config_hint: str

class KestraFlowYAML(BaseModel):
    flow: "KestraFlow"
    yaml_content: str
    filename: str

class KestraInput(BaseModel):
    name: str
    type: str
    description: str
    required: bool
    default_value: typing.Optional[str] = None

class QualityReview(BaseModel):
    approved: bool
    score: int
    summary: str
    issues: typing.List[str]
    recommendations: typing.List[str]
    reviewed_artifacts: typing.List[str]

class RAGEvaluation(BaseModel):
    query: str
    response: "RAGResponse"
    faithfulness: float
    relevance: float
    completeness: float
    hallucination_detected: bool
    notes: str

class RAGPipelineConfig(BaseModel):
    name: str
    description: str
    embedding_model: str
    vector_store: str
    chunk_size: int
    chunk_overlap: int
    strategy: RetrievalStrategy
    reranker: typing.Optional[str] = None
    collection_name: str

class RAGQuery(BaseModel):
    query: str
    intent: str
    filters: typing.List[str]
    strategy: RetrievalStrategy
    top_k: int
    rerank: bool

class RAGResponse(BaseModel):
    answer: str
    confidence: float
    sources: typing.List["DocumentChunk"]
    reasoning: str
    follow_up_questions: typing.List[str]
    requires_more_context: bool

class Resume(BaseModel):
    name: str
    email: str
    experience: typing.List[str]
    skills: typing.List[str]

# #########################################################################
# Generated type aliases (0)
# #########################################################################
