# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.AgentTaskResult": types.AgentTaskResult,
    "stream_types.AgentTaskResult": stream_types.AgentTaskResult,

    "types.CodeArtifact": types.CodeArtifact,
    "stream_types.CodeArtifact": stream_types.CodeArtifact,

    "types.CrewOutput": types.CrewOutput,
    "stream_types.CrewOutput": stream_types.CrewOutput,

    "types.DevelopmentTask": types.DevelopmentTask,
    "stream_types.DevelopmentTask": stream_types.DevelopmentTask,

    "types.DocumentChunk": types.DocumentChunk,
    "stream_types.DocumentChunk": stream_types.DocumentChunk,

    "types.KestraFlow": types.KestraFlow,
    "stream_types.KestraFlow": stream_types.KestraFlow,

    "types.KestraFlowTask": types.KestraFlowTask,
    "stream_types.KestraFlowTask": stream_types.KestraFlowTask,

    "types.KestraFlowYAML": types.KestraFlowYAML,
    "stream_types.KestraFlowYAML": stream_types.KestraFlowYAML,

    "types.KestraInput": types.KestraInput,
    "stream_types.KestraInput": stream_types.KestraInput,

    "types.QualityReview": types.QualityReview,
    "stream_types.QualityReview": stream_types.QualityReview,

    "types.RAGEvaluation": types.RAGEvaluation,
    "stream_types.RAGEvaluation": stream_types.RAGEvaluation,

    "types.RAGPipelineConfig": types.RAGPipelineConfig,
    "stream_types.RAGPipelineConfig": stream_types.RAGPipelineConfig,

    "types.RAGQuery": types.RAGQuery,
    "stream_types.RAGQuery": stream_types.RAGQuery,

    "types.RAGResponse": types.RAGResponse,
    "stream_types.RAGResponse": stream_types.RAGResponse,

    "types.Resume": types.Resume,
    "stream_types.Resume": stream_types.Resume,


    "types.AgentRole": types.AgentRole,

    "types.CodeLanguage": types.CodeLanguage,

    "types.DocumentType": types.DocumentType,

    "types.KestraTaskType": types.KestraTaskType,

    "types.RetrievalStrategy": types.RetrievalStrategy,

    "types.TaskStatus": types.TaskStatus,

}